### PR TITLE
Corrected unexpected output error during activation

### LINKED ISSUE #22: Unexpected output during activation
After copying over the activation code into the new structure, it now outputs the following error when activating:

```The plugin generated 458 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.```

screen shot 2015-10-19 at 5 52 12 pm

### PR DESCRIPTION
**Pull request by AGSoftAU**
Fixes #22

Output was an error notice due to the omitted parameter value,
$is_forced. It now defaults to false when no value is present.

### CODE REVIEW

File: trunk/includes/class-simple-staff-list-activator.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ public static function activate( $is_forced ) {
 			update_option( '_staff_listing_custom_name_plural', $default_name_plural );
 		}
 
-		if ( 'forced activation' != $is_forced ) {
+		if ( true == $is_forced ) {
```
Comment (brettshumaker) [inline trunk/includes/class-simple-staff-list-activator.php]: Thanks for this. Change 167 to `if ( true === $is_forced ) {` and this I'll get it merged in.

**Comment by AGSoftAU** [comment]
Whoops. Typo :disappointed:
